### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by thehowl** [thehowl/diffy#1]
- [ ] Frontend
	- [ ] split view
	- [ ] dark mode
	- [ ] homepage form
- [ ] backend
	- [ ] rate limiting
	- [ ] retention policy
	- [ ] s3 integration
	- [ ] tests
	- [ ] glitchtip error reporting
	- [ ] upload from `git diff` (`git diff | curl https://diffy`)
- [ ] infra
	- [ ] dockerization
	- [ ] ci set-up
- [ ] deployment
	- [ ] buy a domain
	- [ ] abuse email / tos / privacy policy
	- [ ] set up on [malcolmx server](https://zxq.co/zxq/malcolmx)

**Comment by thehowl** [comment]
https://cs.opensource.google/go/x/tools/+/master:internal/diffp/diff.go;l=21?q=diff&sq=&ss=go%2Fx%2Ftools

**Comment by Telemaco019** [comment]
S3 + dockerization implemented in https://github.com/thehowl/diffy/pulls
